import 'dart:ui';

/// 캐릭터 타입 열거형 (16종 MBTI)
enum CharacterType {
  estj,
  entp,
  infp,
  istp,
  enfj,
  intj,
  esfp,
  isfj,
  enfp,
  entj,
  esfj,
  estp,
  infj,
  intp,
  isfp,
  istj,
}

/// 공격 타입
enum AttackType {
  wave, // 주변 파동/근접 범위
  homing, // 유도 투사체
  summon, // 소환/창작 계열
  straight, // 직선 관통/정밀 사격
  aura, // 오라/지휘 계열
  blink, // 순간 폭발/전술 타격
  rapid, // 연타/난사
  shield, // 보호막/안정성
}

/// 캐릭터 능력치 데이터
class CharacterData {
  final CharacterType type;
  final String name;
  final String mbti;
  final String title;
  final String role;
  final String description;
  final double maxHp;
  final double attack;
  final double speed;
  final double baseAttackSpeed;
  final double knockbackPower;
  final int pierceCount;
  final double ultCooldown;
  final Color color;
  final AttackType attackType;
  final bool isFreeCharacter;
  final String assetPath;
  final String assistText;
  final String iconEmoji;
  final String projectileEmoji;
  final String effectEmoji;
  final String attackLabel;
  final List<String> idleQuotes;

  const CharacterData({
    required this.type,
    required this.name,
    required this.mbti,
    required this.title,
    required this.role,
    required this.description,
    required this.maxHp,
    required this.attack,
    required this.speed,
    required this.baseAttackSpeed,
    this.knockbackPower = 0.0,
    this.pierceCount = 1,
    required this.ultCooldown,
    required this.color,
    required this.attackType,
    required this.isFreeCharacter,
    required this.assetPath,
    required this.assistText,
    required this.iconEmoji,
    required this.projectileEmoji,
    required this.effectEmoji,
    required this.attackLabel,
    required this.idleQuotes,
  });
}

String attackProjectileEmoji(AttackType type) {
  switch (type) {
    case AttackType.wave:
      return '📋';
    case AttackType.homing:
      return '💡';
    case AttackType.summon:
      return '🌸';
    case AttackType.straight:
      return '🔧';
    case AttackType.aura:
      return '✨';
    case AttackType.blink:
      return '📄';
    case AttackType.rapid:
      return '🎤';
    case AttackType.shield:
      return '🛡️';
  }
}

List<String> characterEffectBurst(CharacterData data, int count) {
  final seeds = <String>[data.projectileEmoji, data.effectEmoji];
  return List<String>.generate(count, (index) => seeds[index % seeds.length]);
}

class MbtiCharacters {
  static const List<CharacterData> all = [
    CharacterData(
      type: CharacterType.estj,
      name: '칼퇴 부장님',
      mbti: 'ESTJ',
      title: '엄격한 관리자',
      role: '🛡️ 탱커',
      description: '결재판을 방패처럼 드는 현장 관리자.\n묵직한 파동으로 주변을 밀어낸다.',
      maxHp: 110,
      attack: 7,
      speed: 80,
      baseAttackSpeed: 1.0,
      knockbackPower: 120,
      pierceCount: 99,
      ultCooldown: 25,
      color: Color(0xFF4A90D9),
      attackType: AttackType.wave,
      isFreeCharacter: true,
      assetPath: 'characters/estj.png',
      assistText: '[동료] ESTJ: 내 뒤로! 칼퇴 방벽 전개!',
      iconEmoji: '💼',
      projectileEmoji: '📋',
      effectEmoji: '🛡️',
      attackLabel: '결재 파동',
      idleQuotes: ['오늘 야근은 없다.', '다들 집중해!', '결재선은 내가 정리하지.'],
    ),
    CharacterData(
      type: CharacterType.entp,
      name: '아이디어 천재',
      mbti: 'ENTP',
      title: '논쟁을 즐기는 변론가',
      role: '🧠 트릭스터',
      description: '번뜩이는 아이디어를 유도탄처럼 던진다.\n적을 집요하게 따라붙는 교란형 딜러.',
      maxHp: 90,
      attack: 8,
      speed: 85,
      baseAttackSpeed: 0.9,
      knockbackPower: 30,
      ultCooldown: 20,
      color: Color(0xFF9B59B6),
      attackType: AttackType.homing,
      isFreeCharacter: true,
      assetPath: 'characters/entp.png',
      assistText: '[동료] ENTP: 다 비켜봐! 아이디어 폭격 간다!',
      iconEmoji: '💣',
      projectileEmoji: '💡',
      effectEmoji: '🧨',
      attackLabel: '발상 추적탄',
      idleQuotes: ['이거 완전 재밌어지겠는데?', '막히면 규칙을 바꾸면 되지!', '좋아, 더 엉뚱하게 가보자.'],
    ),
    CharacterData(
      type: CharacterType.infp,
      name: '감성 디자이너',
      mbti: 'INFP',
      title: '열정적인 중재자',
      role: '💚 힐러',
      description: '감정과 상상을 꽃잎처럼 흩뿌린다.\n회복과 소환을 겸하는 안정형 서포터.',
      maxHp: 95,
      attack: 7,
      speed: 85,
      baseAttackSpeed: 0.95,
      ultCooldown: 15,
      color: Color(0xFFE91E8C),
      attackType: AttackType.summon,
      isFreeCharacter: false,
      assetPath: 'characters/infp.png',
      assistText: '[동료] INFP: 조금 쉬어가요. 힐링 장막!',
      iconEmoji: '💖',
      projectileEmoji: '🌸',
      effectEmoji: '🌿',
      attackLabel: '감성 소환',
      idleQuotes: ['잠깐 숨 돌리는 것도 필요해요.', '마음이 다치면 오래 가거든요.', '조용히 끝낼 수 있으면 좋겠네요.'],
    ),
    CharacterData(
      type: CharacterType.istp,
      name: '야근의 달인',
      mbti: 'ISTP',
      title: '만능 재주꾼',
      role: '⚔️ 누커',
      description: '공구와 감각으로 전장을 꿰뚫는다.\n직선 관통 공격에 특화된 해결사.',
      maxHp: 94,
      attack: 8.2,
      speed: 88,
      baseAttackSpeed: 0.9,
      knockbackPower: 10,
      pierceCount: 3,
      ultCooldown: 30,
      color: Color(0xFFE74C3C),
      attackType: AttackType.straight,
      isFreeCharacter: false,
      assetPath: 'characters/istp.png',
      assistText: '[동료] ISTP: 길 비켜. 한 줄로 정리한다.',
      iconEmoji: '🔧',
      projectileEmoji: '🔧',
      effectEmoji: '⚙️',
      attackLabel: '정비 관통탄',
      idleQuotes: ['말보다 손이 빠르지.', '복잡하면 뜯어보면 된다.', '빨리 끝내고 집에 가자.'],
    ),
    CharacterData(
      type: CharacterType.enfj,
      name: '팀의 맏형',
      mbti: 'ENFJ',
      title: '정의로운 사회운동가',
      role: '🎯 서포터',
      description: '팀 분위기를 끌어올리는 중심축.\n오라와 버프로 아군 흐름을 끌어올린다.',
      maxHp: 100,
      attack: 7,
      speed: 85,
      baseAttackSpeed: 0.9,
      knockbackPower: 20,
      ultCooldown: 22,
      color: Color(0xFFFFD700),
      attackType: AttackType.aura,
      isFreeCharacter: false,
      assetPath: 'characters/enfj.png',
      assistText: '[동료] ENFJ: 다들 힘내자! 리더십 오라!',
      iconEmoji: '✨',
      projectileEmoji: '✨',
      effectEmoji: '📣',
      attackLabel: '격려 오라',
      idleQuotes: ['우린 같이 가야 해!', '분위기는 내가 살릴게!', '서로 챙기면 훨씬 강해져.'],
    ),
    CharacterData(
      type: CharacterType.intj,
      name: '전략 기획자',
      mbti: 'INTJ',
      title: '용의주도한 전략가',
      role: '🗡️ 암살자',
      description: '계산된 타이밍에 빈틈을 베어낸다.\n순간 폭발과 약점 타격에 강한 전술형 딜러.',
      maxHp: 90,
      attack: 7.5,
      speed: 93,
      baseAttackSpeed: 0.86,
      pierceCount: 2,
      ultCooldown: 28,
      color: Color(0xFF00BCD4),
      attackType: AttackType.blink,
      isFreeCharacter: false,
      assetPath: 'characters/intj.png',
      assistText: '[동료] INTJ: 허점 확보. 전술 타격 개시.',
      iconEmoji: '🗡️',
      projectileEmoji: '📄',
      effectEmoji: '🗡️',
      attackLabel: '계획 섬광',
      idleQuotes: ['계획대로만 가면 된다.', '예상 범위 안이다.', '감정보다 효율이 먼저다.'],
    ),
    CharacterData(
      type: CharacterType.esfp,
      name: '분위기 메이커',
      mbti: 'ESFP',
      title: '자유로운 영혼의 연예인',
      role: '💥 파이터',
      description: '무대를 장악하듯 빠르게 몰아친다.\n짧은 템포의 난사와 연타에 특화됐다.',
      maxHp: 90,
      attack: 6.8,
      speed: 94,
      baseAttackSpeed: 0.82,
      knockbackPower: 5,
      ultCooldown: 18,
      color: Color(0xFFFF9800),
      attackType: AttackType.rapid,
      isFreeCharacter: false,
      assetPath: 'characters/esfp.png',
      assistText: '[동료] ESFP: 스포트라이트 온! 파티 타임!',
      iconEmoji: '🔥',
      projectileEmoji: '🎤',
      effectEmoji: '🎉',
      attackLabel: '무대 난사',
      idleQuotes: ['좋아, 이제 분위기 탄다!', '화끈하게 가보자고!', '이길 때도 멋있어야지!'],
    ),
    CharacterData(
      type: CharacterType.isfj,
      name: '살림꾼 사원',
      mbti: 'ISFJ',
      title: '용감한 수호자',
      role: '🛡️ 수호자',
      description: '팀을 지키는 조용한 버팀목.\n보호막과 회복으로 버티는 안정형 캐릭터.',
      maxHp: 110,
      attack: 7,
      speed: 80,
      baseAttackSpeed: 1.0,
      knockbackPower: 150,
      ultCooldown: 25,
      color: Color(0xFF4CAF50),
      attackType: AttackType.shield,
      isFreeCharacter: false,
      assetPath: 'characters/isfj.png',
      assistText: '[동료] ISFJ: 안전 우선! 보호막 먼저!',
      iconEmoji: '🛡️',
      projectileEmoji: '🛡️',
      effectEmoji: '💚',
      attackLabel: '안전 방벽',
      idleQuotes: ['제가 옆에서 지킬게요.', '무리하지 않는 게 제일 중요해요.', '다 같이 살아남아야 하니까요.'],
    ),
    CharacterData(
      type: CharacterType.enfp,
      name: '컬러 플래너',
      mbti: 'ENFP',
      title: '재기발랄한 활동가',
      role: '🌈 크리에이터',
      description: '아이디어를 색채 폭죽처럼 펼친다.\n창작물을 소환해 전장을 휘젓는 감성형 딜러.',
      maxHp: 92,
      attack: 7.4,
      speed: 93,
      baseAttackSpeed: 0.88,
      ultCooldown: 19,
      color: Color(0xFFBA68C8),
      attackType: AttackType.summon,
      isFreeCharacter: false,
      assetPath: 'characters/enfp.png',
      assistText: '[동료] ENFP: 상상력 풀개방! 컬러 러시!',
      iconEmoji: '🌈',
      projectileEmoji: '🖌️',
      effectEmoji: '🎨',
      attackLabel: '스케치 소환',
      idleQuotes: ['새 아이디어 하나 떠올랐어!', '틀에 갇히면 재미없잖아?', '색감 좋다. 오늘 느낌 왔어!'],
    ),
    CharacterData(
      type: CharacterType.entj,
      name: '작전 총괄',
      mbti: 'ENTJ',
      title: '대담한 통솔자',
      role: '👑 지휘관',
      description: '지휘봉과 태블릿으로 흐름을 장악한다.\n강한 오라와 전술 압박으로 판을 굴린다.',
      maxHp: 102,
      attack: 7.5,
      speed: 88,
      baseAttackSpeed: 0.92,
      knockbackPower: 24,
      ultCooldown: 23,
      color: Color(0xFF8E244D),
      attackType: AttackType.aura,
      isFreeCharacter: false,
      assetPath: 'characters/entj.png',
      assistText: '[동료] ENTJ: 전열 정비! 지휘권은 내가 잡는다!',
      iconEmoji: '👑',
      projectileEmoji: '📍',
      effectEmoji: '📊',
      attackLabel: '지휘 압박',
      idleQuotes: ['판은 내가 짠다.', '우왕좌왕할 시간 없다.', '이길 방법부터 정리하지.'],
    ),
    CharacterData(
      type: CharacterType.esfj,
      name: '복지 담당',
      mbti: 'ESFJ',
      title: '사교적인 외교관',
      role: '☕ 케어러',
      description: '간식 바구니와 커피로 팀을 살핀다.\n보호와 유지력에 강한 생활형 서포터.',
      maxHp: 106,
      attack: 6.8,
      speed: 82,
      baseAttackSpeed: 0.98,
      knockbackPower: 110,
      ultCooldown: 24,
      color: Color(0xFFC9A35C),
      attackType: AttackType.shield,
      isFreeCharacter: false,
      assetPath: 'characters/esfj.png',
      assistText: '[동료] ESFJ: 일단 챙겨! 회복 물자 투입!',
      iconEmoji: '🧺',
      projectileEmoji: '☕',
      effectEmoji: '🎖️',
      attackLabel: '케어 바리어',
      idleQuotes: ['다들 밥은 먹었죠?', '분위기 흔들리면 먼저 챙겨야 해요.', '혼자 버티지 말고 말해요.'],
    ),
    CharacterData(
      type: CharacterType.estp,
      name: '현장 쇼맨',
      mbti: 'ESTP',
      title: '대담한 사업가',
      role: '⚡ 돌격수',
      description: '메가폰으로 흐름을 흔들며 정면 돌파한다.\n넉백이 강한 파동형 브루저.',
      maxHp: 97,
      attack: 7.4,
      speed: 92,
      baseAttackSpeed: 0.88,
      knockbackPower: 85,
      pierceCount: 99,
      ultCooldown: 19,
      color: Color(0xFFFFB300),
      attackType: AttackType.wave,
      isFreeCharacter: false,
      assetPath: 'characters/estp.png',
      assistText: '[동료] ESTP: 비켜! 현장은 내가 뚫는다!',
      iconEmoji: '🏆',
      projectileEmoji: '📣',
      effectEmoji: '⚡',
      attackLabel: '쇼크 웨이브',
      idleQuotes: ['생각보다 몸이 먼저 나가야 할 때가 있지.', '지금이 타이밍이네.', '판 커졌네, 재밌다!'],
    ),
    CharacterData(
      type: CharacterType.infj,
      name: '통찰 멘토',
      mbti: 'INFJ',
      title: '선의의 옹호자',
      role: '🔮 오라클',
      description: '수정구와 기록으로 흐름을 꿰뚫는다.\n직감형 유도탄으로 위험 지점을 먼저 지운다.',
      maxHp: 92,
      attack: 7.8,
      speed: 87,
      baseAttackSpeed: 0.94,
      ultCooldown: 24,
      color: Color(0xFFCE93D8),
      attackType: AttackType.homing,
      isFreeCharacter: false,
      assetPath: 'characters/infj.png',
      assistText: '[동료] INFJ: 흐름이 보여. 통찰 구체 발사.',
      iconEmoji: '📚',
      projectileEmoji: '🔮',
      effectEmoji: '✨',
      attackLabel: '예지 추적탄',
      idleQuotes: ['겉으론 조용해도 다 보이거든요.', '조금만 더 가면 흐름이 바뀌어요.', '누가 흔들리는지 먼저 챙겨야 해요.'],
    ),
    CharacterData(
      type: CharacterType.intp,
      name: '로직 엔지니어',
      mbti: 'INTP',
      title: '호기심 많은 사색가',
      role: '💻 분석 딜러',
      description: '노트북과 실험 정신으로 전장을 계산한다.\n정밀 직선 공격과 관통에 특화된 논리형 딜러.',
      maxHp: 88,
      attack: 7.9,
      speed: 90,
      baseAttackSpeed: 0.9,
      pierceCount: 2,
      ultCooldown: 26,
      color: Color(0xFFA94442),
      attackType: AttackType.straight,
      isFreeCharacter: false,
      assetPath: 'characters/intp.png',
      assistText: '[동료] INTP: 계산 끝. 관통 경로 고정.',
      iconEmoji: '🧠',
      projectileEmoji: '💻',
      effectEmoji: '📐',
      attackLabel: '로직 관통탄',
      idleQuotes: ['잠깐, 이건 더 효율적인 방법이 있어.', '흥미롭네. 데이터가 쌓이고 있어.', '결론만 맞으면 과정은 다듬으면 된다.'],
    ),
    CharacterData(
      type: CharacterType.isfp,
      name: '감각 조형가',
      mbti: 'ISFP',
      title: '호기심 많은 예술가',
      role: '🎨 아티스트',
      description: '팔레트와 조각상으로 감각적인 환영을 만든다.\n부드러운 소환형 압박에 특화된 감성 캐릭터.',
      maxHp: 96,
      attack: 7.2,
      speed: 90,
      baseAttackSpeed: 0.9,
      ultCooldown: 18,
      color: Color(0xFF26A69A),
      attackType: AttackType.summon,
      isFreeCharacter: false,
      assetPath: 'characters/isfp.png',
      assistText: '[동료] ISFP: 감각을 따라가. 조형 환영 전개.',
      iconEmoji: '🗿',
      projectileEmoji: '🎨',
      effectEmoji: '🌿',
      attackLabel: '아트 소환',
      idleQuotes: ['말보단 느낌이 먼저 와요.', '색이 맞으면 흐름도 따라와요.', '조용해도, 표현은 확실하게 할 수 있어요.'],
    ),
    CharacterData(
      type: CharacterType.istj,
      name: '정산 실무관',
      mbti: 'ISTJ',
      title: '청렴결백한 논리주의자',
      role: '📚 관리자',
      description: '장부와 계산기로 실수를 지운다.\n튼튼한 방어와 안정적인 운영에 강한 버팀목.',
      maxHp: 108,
      attack: 7.1,
      speed: 78,
      baseAttackSpeed: 1.02,
      knockbackPower: 135,
      ultCooldown: 26,
      color: Color(0xFF4F8CA8),
      attackType: AttackType.shield,
      isFreeCharacter: false,
      assetPath: 'characters/istj.png',
      assistText: '[동료] ISTJ: 장부 확인 끝. 오차 없이 막는다.',
      iconEmoji: '📘',
      projectileEmoji: '🧮',
      effectEmoji: '📎',
      attackLabel: '정산 방벽',
      idleQuotes: ['기본이 무너지면 다 무너져요.', '체크리스트부터 확인하죠.', '정리된 흐름이 제일 강합니다.'],
    ),
  ];

  static CharacterData getByType(CharacterType type) {
    return all.firstWhere((c) => c.type == type);
  }
}
